apiVersion: v1
data:
    client-info.yml: ENC[AES256_GCM,data:rKkDBFcijqLfmuv8pdmWL1iKHxii2XOQMTY5J116p3hZWWpY82fhSgqbdIV0GDe5qOmCzLK4JdcwIdb9ZSqe6un4Ap7dYqyOONDgjFq0HFogQZ8BN/d3eViYe56eVVLERQY+i07oi9U3nOUHzAAtTaob4UWm1p9bdoYEff+OwP6GQq2zjuVE0v8J3iz/IeuJhRFOjSxwE07xiBOJUe/WLxZA6/ejQPztoKbhh5OZETZ+F+dVL8Ai7/nLJFneLkvPG6eYIzSlmL4B+PbU9EbbNRG93ppPcY5PrdPavRSdXfhNppOVMRAmhXeZaNlfxeLkzvRHOAUXnY2RTfwDy6lCp0K6sCP/v/L82aS0ahBtRv95Z9/LCFNRau9lkWrWRMA9cskDuS6Zh2+Tp5qgw5swu1KlvSmY5gUsK6mNxJjJ+dkDA9QrBdTygVie3jSka6XZqh40BT9ZflG+BBMprUVior3olNmfZe7QQ5tUjmGSrt154I41uZfnXINap32BIwUARDgnHYtkLXIrQbn7s4kHPpA7LW6YweB1cTKX1bYs4GU6IWkXh+tcbBF4YlhGcPq0Z442To5bAchq/Kxx2Otzgb+DD1mUxiERI/F/WAAf7sbpuguY9sL8qFlNKjev+EV4Zm6ZH5NaVjjhCcrIUqNVL/R8MiqLcM5pS1ycMhW+dQVyNOlmYU+PWQWqSsN1MGCpzi/cCAEL7r8XlOoZx2KPeqcQ8Iu4juxb6dxk3vK9AMPfKkV0oxT3ldi2Q6yPiC9K,iv:Zo2W4pkpHAFcili4MRh9fsEuQLqgU0i+M9jvQLlc03E=,tag:Z63869OPeOUmPhbF24Rz5w==,type:str]
kind: Secret
metadata:
    name: client-info-secret
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jjf7zau7j8jg43nkrwcztazmneg39vyn9q4tx4sjkg0d0jt6l5wq4w8ek2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBidXJ1MlNvN05BSGZCN0lt
            T0NBbE0wSkROZytZRHVqOHdNTGpsN3NjSUhvCjh2RGJxNXlJQ0UxV2NORXF3UGVt
            QlhxT2pOTFdjVUcyWXNRRFdDbVdmc1UKLS0tIHgzcitNOW1LeFZQWVdzZy9vMmZn
            WDNCVzdqczVjdGRrYzFhckxJVnJ5M28K6XM1NW+o7Nsl42kmW0ScMPDSm0a8iYci
            g0hkbxWytZrdhtUOMURURv5lXe9dfLXl8TDGZ0b5Ez84BG2Ay98SPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-15T15:17:16Z"
    mac: ENC[AES256_GCM,data:kxKypgP6/7PmmLm57jztPbXJX39vyOWckCH/vefMXuGOXiKEkzOOSZq39Xx5HgMbt5lTtuSJMBGcoypTR9oWwIlG8ZxaE+urZwlju+XFmAD2JQs+rhJLjWqIJWKwSxCpw0TO/UUBBrxeQDQvpSWTU4I64yMsHGKB3m4Hk/ZbIV0=,iv:ahpSwVeENR+B5mcNGGtnNpUcWvRsT7+yMFg+ytC6YDA=,tag:39/ermMEGJsYeUHjrOFPdw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
