apiVersion: v1
data:
    client-info.yml: ENC[AES256_GCM,data:Ws7x8n9hQU+HqSoEhOs4o5RL9BShVUowgkDwlUfQdy0ruOElb2Nn2FA6hYzEZ2ZqYL0y0k5A1N+LQTsO0rDCtc8EIJCXjz6MCEElkLwekCdzoIulDT5FzI3/ghKxF9FNP9z9FgcIBjQzF3R/LFnU16Fq1Uz+b96jDAwlGBpmO+APOTixsSYnZPaePp+sR+f3S+Q1mvM22L7TM7Nwbiz+bweE3aIoN/nFO40JbiL34KR67P+hG/CDLRmc+lFdiJHxqBs35iNfQ7yvgf43KEq+dAQ0MGoGVQeLFRF+ClUBoVMprzd8ECJrPw2wByF4lyg6wGlw6rYNaKMcGjFNZjHKh0sdwDD1v5MckREJ7C0BuMyGLsCtphGB5NYp70RBXhDJ1aqLueOYe4Gbx30E2WCgrSZuLmQn21oeklh0JgL3OTrccnHt7iJ7138JGzdrNghdfto5HOwhE0tZtxvY9gjUVaLFpqOv21q/bviSV9BIhQYfW+fUPhAZN069U4SAr/o9m7bfX+8eMT5w0n9i/q3aNSCURP8yv3BOM0oLiTkrSq/P5T1//R7/8C99Ou2+CT+SHvEYK9R8JEbcoPGAWegdFI0uVUdM7w9Cawamq+ulMk6vTFtQrhER0lXsPcKs/aWqSAaOd9EzPGpsAVlEMTz3Riq0OPVFPy+3z2UsjOmAlza8ssgBiiumDBGxjsuoNvh+e9SKmGrF5RENbWlNnjnM+OEirSPTv2SZ20L2DFeieWvsLf0lVST9ULMzesO1C86x,iv:Cc8bBQWbnELNxePovJmgOBUhl32h3HZ96UoTTu69ANc=,tag:4nhNEFD9WXuCrqrKiXkpaA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: client-info-secret
    namespace: synology-csi
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jjf7zau7j8jg43nkrwcztazmneg39vyn9q4tx4sjkg0d0jt6l5wq4w8ek2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrTUJ1N1k0R0ZlZ1M4SjAy
            ekpuOTZtK2dzMitYUjFadEF2Nzh6ZDhxSUM0CmhreEZCc21COW1oVitva2lTWXVI
            WS8wZDhMR05iVWRZYnlsUng0cklteHcKLS0tIFQzL2wvTlFseDJvUG5jbHdoSGJ3
            VU1UOVVLVE9iRElQNjdtWEJmR2RNS0UKHiVkDuUtV1GEsjusRQFpaut2o1IAHwWK
            lghHLjVIvvz96Bn6pvNtucaOJyC+wfqJGZJvCj8B/bJk50/IaUOTkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-02T08:06:05Z"
    mac: ENC[AES256_GCM,data:yZ3pZhDd/mN8QlDtB3w5lWkmk0F50OqfqwCh2EudnEEo6TInP+3EYs3ybCInW1n1eJ0UxFfgRQy4phl4OBn+6d43XycBtqsXSDcApfarN+SchSlZn5IFHAsahldK7XM3w+tFnAlBs9Xlqxla9yR//RIsF2aipPYRw/EYFvdk5EY=,iv:uh63CA+maK73qoitoPWmnsoARAZipP5XTKGYw0hf6/0=,tag:EeMWkHrgfvB4SMi7EcrWcw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
