apiVersion: v1
data:
    client-info.yml: ENC[AES256_GCM,data:VGb0pPhuA2alKWz1+eTbhbFUO7E++hE/JIAjt3oO8+9uwFIpJcAPbr/6XxlvfSxJOQ1wSJOhi9rgZiWFLjFL7PS5T+gGd2yzNb4P3AuT9wgDl4itQf+hubVJfiUPbVmJteCYQ34CVSmtX1WBpQLimSM21W35xOWcACHAKAuVZYAs1jeGHhFB8KsFyugAYLS8PTViADyutRyFpj+bHT1dUYJZyM6rAosGzSsEpKTjNQ2bMuKwb7xAaazmdj4+JdFCXRNh8RXqwaDv3pwkT4bD75JRG+q9moHbEALuWRryHzqq+Jhvn1W1fL3N1DmR/iUknB0E+enkYE1lbdsNcHcLuzZQEEFrPLIYTWUKMqWqAVMTEjfI06KsOJAvPE7GG5lzqcI56Tv8F0jj4LkheGyHWYePhmW+OnU+MIVpFPShVG3IMB3h6zjrNv2Z18V7EKJO9yUPAbEpJLGnvIEqgNpfDpCCSt8Zo7RtKEsaoDCchtC7CEZfwd8ItGZZD01uxFoGMKEBQsDvbh9N0cz65qLkDfOpZ7uAlFwP66wtwuS2tYMGuxYZMLg88toiAchoyrtRp8ViUwLYoJWJTBVbIJtPDeMbzYI3efsgBAr7Gdeay9/1OQ15dbN2eFg3CxhFGlSvi4+0Sbn5NiDQf+0C4f0AixdUH2ASfu40kekvEzIWmairrYczUndFoee83t68cTWT8HcZ6nrAo39l2UIdvC3GsXnCgM8eivLrzzuwKwArzAU62Hef+Ar0q4O/RySHvXhw,iv:y2gl9EDSEw4kV+W/kXGBlBgH8rhbnbGj6TEyaJtBgis=,tag:PpMiRmsQbB45XH45Trw8pQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: client-info-secret
    namespace: synology-csi
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jjf7zau7j8jg43nkrwcztazmneg39vyn9q4tx4sjkg0d0jt6l5wq4w8ek2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBla3Z6WWpIREY0NEJoV1hn
            OStYbW9JRHZtRGJNSE5aQkZkMzc0UWQzRUVjCkROVFZyRXBHWUsyS2VIaFRnNXVt
            V2o2ejVpNGcraVhHd3FRTHE0K3p3VG8KLS0tIDErYUV5ZnZMK280MXNLQWlJTEls
            cGdmUjF6bktSN2lnR0FNSEdtRXFmZkEK+y6XHlzOUyz+kDy+UmZMzbjFifViBMHH
            JhIh4YPTicNCXMjVy08ItjIGWWfZ77SjL7ogo8VW8FYyM0LUHXOpsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-21T08:31:44Z"
    mac: ENC[AES256_GCM,data:kfFD1+nX5RAyCyYi9NWMccv8q1PPFVfZXwDNtCntm4aK+T0QjfHwR5NIjidppO1j22VZGGMRxpJu30jyCMbnfNWbdQKB9Gl86vCuDQSqf5q1d1fKUzeUiQtLnuU9GbBoeinEkwv6fsFUsgUyu77CRMcjIuaAOF8MPoP4XIHryeI=,iv:ivoCIHcNn5E8c+6Fhy/pNN3ToDAZc/8Y+Dq4n3io+pA=,tag:C6k7coz3/1TxqLHwqh4Ajg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
