apiVersion: v1
data:
    MOBILE_DB_URL: ENC[AES256_GCM,data:UENE4EEsWwxvFuPOXL6qVVgtSPvzGQL7H8+Srm48vkynsA/UILBsJRd0J52PZ71j,iv:k3vWImw6Q/UsARN0BUfq/qTjAj8cIxIpGyUSLQxVhQc=,tag:HIFOiUg+iTbONn632g+GMg==,type:str]
kind: Secret
metadata:
    name: moneybud-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jjf7zau7j8jg43nkrwcztazmneg39vyn9q4tx4sjkg0d0jt6l5wq4w8ek2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwYWxydjFleW0yRndLNmJJ
            WWZLdWdrL0lHNU5tNFNlNW1rMVV3eVFxN0VNCnk1Ylp6czAxYS9ZWjNjcWo0RHZS
            RXJEUEprOWU5NTgrRUxEVzErWm9WY0kKLS0tIHJlZ0sySnZmeTQ1aEJxdlZmUkRa
            MHVuZ3dOTlZ6YzVubjc0TGIzWHJINnMKO4Jew2BvSwegDt4Sm8Eva9l4gUxEyWOh
            JrEoTmoTzVauiQP44AKZvf5bEkF5M2VTqYhNfRJF+3slyVqPiitpQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-03T14:09:38Z"
    mac: ENC[AES256_GCM,data:WhrDZw4LJAtlEv+LSVaTfzdDZg1k8MoWfNZ9cJkjErGPzTIo6ZUB9G7YTohSdeuJPPsCuxwEdEV1ziUp1gOnGRgfvIjDCMqTqUV3HM340P62UV/dSwAjwaMb1rxCBmluuXOlAmci2IbHTCvNmirQWsgY92JekhZ7ns+atHWPWRk=,iv:0KqyYg9r6LDpmoXPpJfI/ldFTwYlvW6qg1IcWiVtRBI=,tag:EeVvoYCtsbMs4rWHPccJnA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
