apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
spec:
  chart:
    spec:
      chart: keycloak
      sourceRef:
        kind: HelmRepository
        name: keycloak
      version: "24.3.0"
  interval: 1h0m0s
  valuesFrom:
    - kind: ConfigMap
      name: keycloak-values
