apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - keycloak-helmrelease.yaml
  - keycloak-helmrepository.yaml
  - keycloak-namespace.yaml
  - secret.yaml

configMapGenerator:
  - name: keycloak-values
    files:
      - values.yaml=values.yaml

configurations:
  - kustomizeconfig.yaml
