args:
  - "start"

database:
  vendor: postgres
  existingSecret: keycloak-secret
  existingSecretKey: keycloak-db-password

extraEnv: |
  - name: KC_DB_URL_HOST
    valueFrom:
      secretKeyRef:
        name: keycloak-secret
        key: keycloak-db-host
  - name: KC_DB_URL_PORT
    valueFrom:
      secretKeyRef:
        name: keycloak-secret
        key: keycloak-db-port
  - name: KC_DB_USERNAME
    valueFrom:
      secretKeyRef:
        name: keycloak-secret
        key: keycloak-db-user
  - name: KC_DB_URL_DATABASE
    valueFrom:
      secretKeyRef:
        name: keycloak-secret
        key: keycloak-db-name
  - name: KEYCLOAK_ADMIN
    valueFrom:
      secretKeyRef:
        name: keycloak-secret
        key: KEYCLOAK_ADMIN_USER
  - name: KEYCLOAK_ADMIN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: keycloak-secret
        key: KEYCLOAK_ADMIN_PASSWORD
  - name: KC_HOSTNAME
    value: "https://gatekeeper.federicoserini.com"

proxy:
  enabled: true
  mode: forwarded

http:
  relativePath: "/"

extraInitContainers: |
  - name: theme-loader
    image: ghcr.io/federicoserini/homelab-keycloak-theme:latest
    imagePullPolicy: Always
    command: ["cp", "-r", "/theme/homelab-theme", "/themes/"]
    volumeMounts:
      - name: theme
        mountPath: /themes

extraVolumes: |
  - name: theme
    emptyDir: {}

extraVolumeMounts: |
  - name: theme
    mountPath: /opt/keycloak/themes/homelab-theme
