apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mobile-db-data-pvc
  namespace: mobile-db
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synology-iscsi-storage
  resources:
    requests:
      storage: 1Gi
