apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
    spec:
      securityContext:
        runAsUser: 911 # id -u abc
        runAsGroup: 911
        fsGroup: 911
      containers:
        - name: mealie
          image: ghcr.io/mealie-recipes/mealie:v2.7.1
          ports:
            - containerPort: 9000
          volumeMounts::
            - name: mealie-data
              mountPath: /app/data
          securityContext:
            allowPrivilegeEscalation: false
          envFrom:
            - secretRef:
                name: mealie-secret
          readinessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 15
      volumes:
        - name: mealie-data
          persistentVolumeClaim:
            claimName: mealie-data-pvc
