apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:Xg1ywQfKEBe0hTs9MiDtB66wAbVptC0C7iH0LByXQ6LYaSmcxdJoCkqcAfqUc3/UgWHg2C1Q2aSv1FRx2bVs5pDMz1tlp22sONbCEjbgD4WiOrEGizJ2h26tKucQlwIdpTfI7JGnXYGSvv8xjUHNd/MBW3Oixdof5SUuRArIRNqp4YxqCKpMkqmrBakmCYLyqR3F+dGyNbVZbckRpoKqzWsCDZydnG5sL3eCt1giIKfx/eHt6DypTgCSKkgdNqxMjT5hUQCD41Q0y1o4HUpASNxUOStXiIpuAZwDc2RfTqj7FsO51j5smmjlY0K798xQAbW8/2fBLcYvif2HRdh2ns3oHt2DazhBtgl8k0iYWUJThhEMddKsnSp4ROcTdT+/gZoqWBK/yZxtIOuf6pOs1BF/tsv0B1hh6ISceg==,iv:tiffFkNSEYeWUfp5biUtxWx2pLlOLXZ47vQlaEf7c1Y=,tag:HJjZI7tX7kw/XIhx1Onx8g==,type:str]
kind: Secret
metadata:
    name: ghcr-login-secret
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jjf7zau7j8jg43nkrwcztazmneg39vyn9q4tx4sjkg0d0jt6l5wq4w8ek2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5dGt5UEExR2dTRFpIM0Jr
            TndVMTNpVEdtRGVRRm1oNXFZOVZ6U01aWTJvCmI2MDB5N1poMkZzbFE4aStkOStC
            YWpJYTBXMHBCd2VhRTZFVlIvK2J2MHMKLS0tIGs2dWRUbWREV1ZvaEdIbE5rTkFI
            dlFiSUszbjFoMCt2ZEowNXF2WVU3eUUKwO5T4r/m5qTlPPYe9E21EcZX7MPQHd+v
            G1+wBZavvuWXO4fIJfdzJtoUEIcFJHhRxpgyYrC98VuiUd49W8qAyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-28T12:45:20Z"
    mac: ENC[AES256_GCM,data:o/idEKekFi0MeFklKateFf0OdRUxdxku1mC/lhqCyWpKiju4wxIGHPGcDgQwpyjJV3+r5fg2VSN8Y2iW7D88hKerP6gnREsoP4ykavELYOatak4lzmxHPE0GAvqiBATjCIdp76ME71b9zkknIeiv1mAJEMAELHDfHzrK/G6Kmro=,iv:Go5x0j94TXSSipA18/4HCvYP87JjszOJl8DpuekzMcU=,tag:MJAH7N/Wsbwy4HnJk2IhEA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
