apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mobile-db
resources:
  - ../../base/mobile-db/
  - cloudflare.yaml
  - cloudflare-secret.yaml
  - mobile-db-secret.yaml
  - ghcr-login-secret.yaml
