apiVersion: v1
data:
    ADMIN_PASSWORD_HASH: ENC[AES256_GCM,data:KcF2lpP8uP8sS8fdH0lKLjvP3s/Hpv/0dElB/NFR0N5epTgUsXbZYkqvev0s+DB7K0ItsWMzFvkVqLdpkZdRgIIl6Q/d5hlK8lSttZVyufs=,iv:4xToIkDIXFDnIkhU22NE1MxO5JVhtfdjUlFY6G6PnN4=,tag:3iZeUdVzOLa3apMsbnV4cw==,type:str]
    DB_ENCRYPTION_KEY: ENC[AES256_GCM,data:kt+6vgY8H9o53iQG7hXujKyZq3KpcFdfqtJNsiox0FGK1DP6qQFviqEwpdDWthzDC34yYoO/86uT+L58,iv:v1j4PjynZjTx41OgYpRcwvRpg01IsLYSlDelEKQwEnQ=,tag:kClL7pEuvaGWp3VewxL9eA==,type:str]
    KEYCLOAK_REALM: ENC[AES256_GCM,data:IrCY2JjaSF0=,iv:rEB5kIHEn5tS3XssTCwWJOnMnDQV0wiu/qzCNkq7DmQ=,tag:tpbtEDCNxED+EL15hLprow==,type:str]
    KEYCLOAK_URL: ENC[AES256_GCM,data:0jOB/3VKJRTBso7wcLU5ugM+xXUD39nZ7Gsgt1jK59iiGauW2AhdZlMUYA5k3DLZMUFCgw==,iv:QPwJ9Qiem3+0tY7v3JoW4MRmSHXx+eVnt+xadQtLSfI=,tag:mrQQ1hnQoac0MaCL9PNYZg==,type:str]
kind: Secret
metadata:
    name: mobile-db-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jjf7zau7j8jg43nkrwcztazmneg39vyn9q4tx4sjkg0d0jt6l5wq4w8ek2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHRG5hNlZIMUkyanBWYmlT
            ZHZiQTRZQVdROUlwTElOU3ErQUdlaDEzSFd3CjhOTXdnS2k1d1o5cG92QjZ5Q1E2
            NlNpV05KNW1xRUllVGdzanpLSERpamMKLS0tIGRZemlseXA4V2M2R3RIaHZXVWM1
            OGw2d2VBV2ZDK09Hdyszd0VOWWkyTDgKV0lhk7blnVzHwfNsx9O4TxXXZm4QT8+J
            jQMhC5W59jlvbpI6eFx18+E1iiHoirhd15K0Mv0SkFqVz08vPkxeBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-30T15:51:46Z"
    mac: ENC[AES256_GCM,data:1xD17vajuSlY8N4/0fC8jZ8oY6NEJ1btViN+QOF8MGqvffzLpm6w0VVh7445xCBn4qQZwwve1EA6h+s80fL9eXamvdzrnXI03nrGg6sXhPPzI3X9D91kJzYTRatzd/MvfNJ99IrsW7a0jQ6C78+D+CdV+GklicB63A0ZZRFO5NM=,iv:qj6i76nh3japlfKlqu6cYV3sys59r/ons8iLQ0YdUG8=,tag:bPEu1vzC2vOwTmZEgI9FIQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
