apiVersion: v1
data:
    ADMIN_PASSWORD_HASH: ENC[AES256_GCM,data:KcF2lpP8uP8sS8fdH0lKLjvP3s/Hpv/0dElB/NFR0N5epTgUsXbZYkqvev0s+DB7K0ItsWMzFvkVqLdpkZdRgIIl6Q/d5hlK8lSttZVyufs=,iv:4xToIkDIXFDnIkhU22NE1MxO5JVhtfdjUlFY6G6PnN4=,tag:3iZeUdVzOLa3apMsbnV4cw==,type:str]
    DB_ENCRYPTION_KEY: ENC[AES256_GCM,data:kt+6vgY8H9o53iQG7hXujKyZq3KpcFdfqtJNsiox0FGK1DP6qQFviqEwpdDWthzDC34yYoO/86uT+L58,iv:v1j4PjynZjTx41OgYpRcwvRpg01IsLYSlDelEKQwEnQ=,tag:kClL7pEuvaGWp3VewxL9eA==,type:str]
    KEYCLOAK_REALM: ENC[AES256_GCM,data:KV4QjrTI5g3DKMde,iv:NMsICnahezhHzvt2tLcjK31Kt2bFzQ1zQh7uZ6caDr4=,tag:y0ohr3tOzwRo4Igr/eH1rg==,type:str]
    KEYCLOAK_URL: ENC[AES256_GCM,data:0jOB/3VKJRTBso7wcLU5ugM+xXUD39nZ7Gsgt1jK59iiGauW2AhdZlMUYA5k3DLZMUFCgw==,iv:QPwJ9Qiem3+0tY7v3JoW4MRmSHXx+eVnt+xadQtLSfI=,tag:mrQQ1hnQoac0MaCL9PNYZg==,type:str]
kind: Secret
metadata:
    name: mobile-db-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jjf7zau7j8jg43nkrwcztazmneg39vyn9q4tx4sjkg0d0jt6l5wq4w8ek2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHRG5hNlZIMUkyanBWYmlT
            ZHZiQTRZQVdROUlwTElOU3ErQUdlaDEzSFd3CjhOTXdnS2k1d1o5cG92QjZ5Q1E2
            NlNpV05KNW1xRUllVGdzanpLSERpamMKLS0tIGRZemlseXA4V2M2R3RIaHZXVWM1
            OGw2d2VBV2ZDK09Hdyszd0VOWWkyTDgKV0lhk7blnVzHwfNsx9O4TxXXZm4QT8+J
            jQMhC5W59jlvbpI6eFx18+E1iiHoirhd15K0Mv0SkFqVz08vPkxeBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-03T14:46:48Z"
    mac: ENC[AES256_GCM,data:it4/lDcHc94yfagv+yLQvOMC4fbBLX9+Sq2lzSsArnLm0sMs4quP/2qb7RcZDPljeUaES3yXVcXuVijieWo+gKJMwNXemmXRrozHSV6QIdyVV5ZjWHi43dzacqfFj1xge5Jh3uiRzSDMH2j15sHLFsmpbjp78LfnSK8w4rJ3yQw=,iv:2O/cjNNdBFIcR5AT+KkTugdrXAfzS/TqnnNGitv29y4=,tag:yx7agIA6zrA9f/ZRl8bOyw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
