apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:LXlcEd2ObcJeJSVeb079alPZQEGMNMJbPVyn5h2FZF3oZA4IHmYfyNPR568CDVQ6De/ORjtawh6cpagwTClTEvVpdIVblXgFHhGHLVe/VoEXGOngM17BOTpQi0Qh2uuV1aZR5GY4OTbtjDwP4Yw/dz3F8aNiWu2Xbpn/X/zhRyPEDagHhwXU/7g8yaoc9ezaLrREW4bZyeebw5E0pmKuG802SDu11pfIdI+n4sCAN3LQ1/yRC6jGgxfRJ/cb2HReHAidz44dadUV0uwU3yBGOSLFvGtEosO1,iv:Jy4O6FELuyRVkL5NKLYyqEEjfCqlkS7COFAThRfo680=,tag:BJFQbgftkg/PfezVI5jlXA==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jjf7zau7j8jg43nkrwcztazmneg39vyn9q4tx4sjkg0d0jt6l5wq4w8ek2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2U2VHdVpQZXViazFkOHJ5
            ZWFFUzVHUERsNlpmQjdZN2pUTjJBV2djeEFvCnBmQ2hSbWRwVFBCTyt4YVU2QmNn
            L1V1QzlOSmVlWjUwbEtRdG43UFhQYVEKLS0tIEJlTkVoYmt4d21COTlPS2xaakdR
            cThRS2c2Sy92L1pkK1R2SUhQaUI3cUUKqeWtNb4S9N5zwvPj4bqBjpkZxhfBdCUV
            18yf0dZslIQvmLQipDir30VU6B4o0j7+VDmeN/Vu5VMB6e6Sf1i6jg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-30T15:51:46Z"
    mac: ENC[AES256_GCM,data:KaCeyo7QazXdYob+qMRDR+TJGFgCpHRED8YSmZfPT9NJzFQ7Wl8hlYfUrrR+YeReo5f65jPS3PGwxPAmFosh1QIMxdAEU06yP2qhDr7SELJ/ykKyQe4UeLRvzGO2s23Du4Mp/HfJBPPevusady3Zg4DSQYGWjrqckSyVpRkydXE=,iv:lbWKYeBfIv0/jfxbMrlpUXeA6O+dm2EEx8238AOJAWQ=,tag:x1SWKalVI2EotmoBks61Lw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
