apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - external-dns-namespace.yaml
  - external-dns-helmrepository.yaml
  - external-dns-helmrelease.yaml
  - secret.yaml

configMapGenerator:
  - name: external-dns-values
    files:
      - values.yaml=values.yaml

configurations:
  - kustomizeconfig.yaml
