apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mongodb-operator
spec:
  chart:
    spec:
      chart: community-operator
      sourceRef:
        kind: HelmRepository
        name: mongodb-operator
      version: "0.13.0"
  interval: 1h0m0s
