apiVersion: v1
data:
    APP_URL: ENC[AES256_GCM,data:Fik7Xx5iE3ibooDvamMlTpepyDAKYQMf5+xl+Y5BnUzQctE1EB123tYonMcESh1D,iv:2qhtopuFBBMxXj1+GdtodnkD/DB7c3LjB3O8uq5Q3Jo=,tag:xIsLQk+FUVXYbDJBbz3yyw==,type:str]
    DB_DATABASE: ENC[AES256_GCM,data:/cPvAZ/1qAY=,iv:ZlOeQKWHJvuYEc66bKvZGzolA22/tIEYhzeUaJ2b3fA=,tag:UdosPfgm+pjRiME2abeeWA==,type:str]
    DB_HOST: ENC[AES256_GCM,data:VfNLpMJbqJTDZi4KtDgQq7/a1vKVHePyXXDFTzWrem7+19DPKqw6JA==,iv:zhPfSgd32esATVSOW16DBEZfdgCOb74wJpYTJtE3CV8=,tag:qCOwz0ubNzTxEpFsR7XC/Q==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:P5tpGKqHggObU7+n,iv:0GFu8uaR+E+WzFAPyqV0snJd5CN7aeNP1YmH7R335CE=,tag:+qNwS5aP6KbU3Pw8tnvo3g==,type:str]
    DB_PORT: ENC[AES256_GCM,data:6Wwr6bGXugY=,iv:obhlP20kQvYsQ8eivrtPcT61cBS+5CUXJSneQK/awF4=,tag:nKN8MXorn309/nNqE1tCHQ==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:gvRf1N04JwQ=,iv:KgxmG2r26AUnHzYq47ycdHrJOSRT6ClvR9tIUnZh3Fc=,tag:VdD5Cn8orKGT40HQbWnAqw==,type:str]
    PGID: ENC[AES256_GCM,data:UiRRZfkjjWA=,iv:FlvZTrtR1nb97BONcQPorMnFqqfCbFzzYwWE7ZTFnaQ=,tag:PgOGV5JsHBUqizxyU8xrtQ==,type:str]
    PUID: ENC[AES256_GCM,data:bsGhcVogfQM=,iv:zDm+0XkaL/PdSYqxNDnNJwsW2Vq/bF7ssT+Ste1p7gA=,tag:vbXFU/EWRrN7MRUlrObWSw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: bookstack-secret
    namespace: bookstack
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jjf7zau7j8jg43nkrwcztazmneg39vyn9q4tx4sjkg0d0jt6l5wq4w8ek2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSQ29lZmRCdG4xdXhNQTky
            R3hsVjlqQTZoL01hQjF6TXN6L3JHMGU2ZEdRCldzY2RiWDhBS1VlNEg3b21LV21N
            b29xMFFlcW5qcStLaXpVandaazJkTEkKLS0tIE5wRzJZTDRQWGh4ME5VZE4vOXhq
            OTNZSlBBQjlrQSsrVXE3eGV1NDU2Sm8K9ujsQ0LpyhVOcEzacz+4fmknseiVQ+tt
            ZteVallnCkHa/KF1nT6p91O3IQ7PNJjfzyptu4rniHBa978rMkqNIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-20T18:19:25Z"
    mac: ENC[AES256_GCM,data:eg9kGFHO1/98Njqai7tpWcsCXDvA9E4eDnWFMHQPXR87awgE/hankhyl+YR64oa5PkkbYhzkW4nqvGrf+/ZIOZqNnoqAd4RTx5pj8ObaQP0rV1W6odKfKEz7jSsIe0RY1yzKcP8jUesIp1hNgfvvY2aeCxWYxbKIytp1oIm/g6o=,iv:k8ep7pWhUKHWcgFwoBeaAVn21dpey0OqytoOrwoZhRs=,tag:m5WZFpwxKH1fE0ruhoPzqw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
