apiVersion: v1
data:
    BS_TOKEN_ID: ENC[AES256_GCM,data:BkNZnfcNNSf9gCxO48Vgimie0uwgwrhEHeFoZEltFtWRtNlUJ6XYwoTRJxk=,iv:H4oOqNu7C8DdR4en1HdfMMfAVIU8/4ERmzsyvvkaj3c=,tag:onzWWBRjKO2O9szf2+I9Cw==,type:str]
    BS_TOKEN_SECRET: ENC[AES256_GCM,data:igZ5yaUmLKADHLtj3RKQsTmYHiWUeJMrReJD5Pu4k0ZmIoDR8qwbTaOERhs=,iv:n2GHShQbtggFTayueZ8s8AfuAk8UjhLDuFbIGgo4cl4=,tag:lPd4tqvxFpmS5WC6QN8S1w==,type:str]
    REPO: ENC[AES256_GCM,data:UB2YPDTA/R+WHqCbI0sMDttvhZ3gCdIUdHGARx289lZlEb5P7ytNDLrOQrzZPgP++DtQ8h1mPolq2q+PZoND504SQNJ3/RtRssyeblLGkiiaHWHqubUqfdxL+KSt/iXp9dwzHtjE2Ufc6PduFtjsEH/sWiMkPOvjLl4NGpDbit1d8ry4odTULXC5+SYmSrDrliALEUwhkO/3r7iBI9aQjAyhEWUC8oF0jVY/MTj7JEbnSxUObZRwgag4G3g=,iv:ZUN2DVeLZGWDkNmj9Az9pBcRZ8OAVPs3Gn7XOjfxC08=,tag:IlL9Q2LmVTu1z8lzDfr5Fg==,type:str]
    REPO_ROOT_FOLDER: ENC[AES256_GCM,data:CtNbf2sxP4jfiMHh,iv:5du06A0ahuTKLNPZZ2f9Mqtp/gioZLb1OtB9H7eyTto=,tag:kb8A2xJJ6HK8fQC0962thQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: bookstack-backup-secret
    namespace: bookstack
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jjf7zau7j8jg43nkrwcztazmneg39vyn9q4tx4sjkg0d0jt6l5wq4w8ek2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwUDBhczBRTGZaSUZCejVO
            OCthVWpHUnVycnF5WFB5STRTcGdBZ2hJYms0Cm1sNVg0Nkk4eVhDOWJwZEdmREVW
            VjFUMHE0dWt3S3NxWkJsNmpJaUcvRjQKLS0tIEFZWTduaENhUGVhbWRoY3pyVURq
            SnNyMjFNMlQ1TFZVVkhDK3BabGdhWWMKEk3+GRQDGhXLQQD6aQ8jGfkoxOvpkhNv
            jZ3cjKc0DYKhKAM2IVHhHPv0fu71twWvzeakbpbNd+rUb9c4tXJE7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-01T10:54:13Z"
    mac: ENC[AES256_GCM,data:L7JAn/n5QsUAmrmA+J3F2Av1XieQzHdzf/UWEJXIhQn7ApRGN+sfm4ua9FyXHlj/wFX3mEncS6zMeaxkiHrmrtI8g7eKjty4wAAbA7nPeCQ/h9NDxmq8FXrWiAFUu1O+gPPiySAQnTHXy0uaYSI8vjdnJKpHhNiisrcTdRuBTGs=,iv:7qxAeeBhITANYTd83eMdkxha1DSqcxGHNJGZkl9QJjI=,tag:aen1USzywKVKvYI1/TDhyg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
