apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-job
spec:
  schedule: "*/10 * * * *" # every 10 minutes
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: backup-container
              image: bitnamisecure/git
              command: ["/bin/sh", "/scripts/backup.sh"]
              volumeMounts:
                - name: backup-storage
                  mountPath: /backup
                - name: script-volume
                  mountPath: /scripts
                  readOnly: true
              envFrom:
                - secretRef:
                    name: bookstack-backup-secret
          volumes:
            - name: backup-storage
              persistentVolumeClaim:
                claimName: bookstack-data-pvc
            - name: script-volume
              configMap:
                name: backup-script
                defaultMode: 0777
