apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:vuWwh4vF7b8Ax69pBjU5P8ivqv9LCySBy8w/VyMjwsDLi/m42GSTuOOAD/yyjp0M5abwUigylWF31WpU0YYz0Mrn7IvrvLbvd/E9Xec+LdtPxRziPcw6opdPCzzxObCai+ZlxsjCpjYrj+kQ/Zyp46oinrXDsU8i8t0P4xdr+0sIkoCPPxLcoOViWUtfRIGYe7pckLzd5xBU2IEMs/i95RdeUpybtk7eJWR/1bT6QQxkQR6m2sSA4EghbI57djNPmkqffADToNMdqYHeVN+dBIBxEvSpP7oT,iv:FsuLP0jqkKw236UvhdagteLsZPMDCg0RUDpAAm9qwbM=,tag:3COpz16U16LR2RxYjh8uVg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
    namespace: bookstack
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jjf7zau7j8jg43nkrwcztazmneg39vyn9q4tx4sjkg0d0jt6l5wq4w8ek2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6aUdtNzN4WFhIOWg0UXBS
            NjdaeWRFMmZWVWdHTjhKUS9rRmJhcisvano4CjNEcXhPSjVUcHBReXY4OVh6UWNX
            NzJteFo3ZWgwUUh3dWZ0ZG1mRGhYc2sKLS0tIFB0T2xJRmViL2xnOTRjZkw3NFF5
            ZW1NQUduWTdidk93WUJTT2tuMzBkbEkKel/YJmuH0eaXUizrJgY0IZf7i3fcda0n
            yl/mU8Hy2g/B/TzcIHjtIr8610SnmNXp6F9EimFGonF6Hv4eFuhDzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-20T17:58:59Z"
    mac: ENC[AES256_GCM,data:XciaDIiZ2DOqubrpknpNp+DPLwXZR7bfFJVzm8aoRr9LV+dtuNVh1hfGSl7huH4DnWpek0Cr9PKJJkI8rO3Of/vUBTH5J0ZigZSqu+5FLZ9//71WaLwx467cfhgt4th3ag4q9g1LVr8VUPmcHEinx4IaE25SxxOqXd81G8s0qUA=,iv:aOFys43KXIntTU1lTLpG2wZVfuijNGCKlCSS3v0VHQM=,tag:vzXCh2cS8RrvMvNC77Wqrg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
