apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstack
  template:
    metadata:
      labels:
        app: bookstack
    spec:
      # uses root for init
      #securityContext:
      #  runAsUser: 1000
      #  runAsGroup: 1000
      #  fsGroup: 1000
      containers:
        - name: bookstack
          image: lscr.io/linuxserver/bookstack:25.05.20250616
          ports:
            - containerPort: 80
          volumeMounts:
            - name: bookstack-data
              mountPath: /bookstack_app_data
          securityContext:
            allowPrivilegeEscalation: false
          envFrom:
            - secretRef:
                name: bookstack-secret
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 30
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 30
      volumes:
        - name: bookstack-data
          persistentVolumeClaim:
            claimName: bookstack-data-pvc
