apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: falco
spec:
  chart:
    spec:
      chart: falco
      sourceRef:
        kind: HelmRepository
        name: falco
      version: "4.20.1"
  interval: 1h0m0s
  values:
    falco:
      customRules:
        custom-rules.yaml: |-
          - list: forbidden_cmd
            items: [apk, curl, wget]
          - macro: container
            condition: container_id != host
          - macro: spawned_process
            condition: evt_type = execve and evt.dir = <
          - macro: shell_procs
            condition: proc.name in (forbidden_cmd)
          - rule: Block Package Managers Execution
            desc: Detect and alert when apk, curl, or wget is executed inside container
            condition: spawned_process and container and shell_procs
            output: "Package manager execution detected in container (command=%proc.cmdline user=%user.name container_id=%container.id)"
            priority: CRITICAL
            tags: [security, container]
