apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: falco
spec:
  chart:
    spec:
      chart: falco
      sourceRef:
        kind: HelmRepository
        name: falco
      version: "4.20.1"
  interval: 1h0m0s
  values:
    collectors:
      # enables metacollector
      kubernetes:
        enabled: true
    json_output: true
    customRules:
      custom-rules.yaml: |-
        - list: forbidden_cmd
          items: [apk, curl, wget]
        - list: kube_namespaces
          items: [bookstack]
        - macro: checked_namespaces
          condition: k8smeta.ns.name in (kube_namespaces)
        - macro: forbidden_procs
          condition: proc.name in (forbidden_cmd)
        - rule: Block Package Managers Execution
          desc: Detect and alert when apk, curl, or wget is executed inside the container
          condition: >
            (spawned_process 
            and container 
            and forbidden_procs
            and checked_namespaces)
            or (spawned_process
            and container 
            and shell_procs
            and proc.tty != 0
            and container_entrypoint
            and not user_expected_terminal_shell_in_container_conditions
            and checked_namespaces)
          output: "Package manager execution detected in container (command=%proc.cmdline namespace=%k8smeta.ns.name user=%user.name pod_uid=%k8smeta.pod.uid, pod_name=%k8smeta.pod.name)"
          priority: CRITICAL
          tags: [security, container]
