apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: falco
spec:
  chart:
    spec:
      chart: falco
      sourceRef:
        kind: HelmRepository
        name: falco
      version: "4.20.1"
  interval: 1h0m0s
  values:
    falco:
      customRules:
        custom-rules.yaml: |
          - rule: Block Package Managers Execution Bookstack
            desc: Detect and alert when apk, curl, or wget is executed inside bookstack container
            condition: container and proc.name in (apk, curl, wget) and k8s.ns.name="bookstack"
            output: "Package manager execution detected in container (command=%proc.cmdline user=%user.name container_id=%container.id)"
            priority: CRITICAL
            tags: [security, container]
